APP = liteos_m
APP_S_SRCS = los_dispatch.S los_exc.S los_start.S
APP_C_SRCS = main.c los_init.c los_memory.c los_task.c los_context.c los_interrupt.c los_timer.c
EXTRA_CLEAN = $(APP).dump
include $(PENGLAI_SDK)/app.mk
